# Generated by Django 4.0.6 on 2023-01-05 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_url', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backimage_url', models.URLField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xcoor', models.IntegerField()),
                ('ycoor', models.IntegerField()),
                ('rotate', models.IntegerField()),
                ('default_sticker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rollpaper.defaultsticker')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rollpaper.paper')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rollpaper.user'),
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=20)),
                ('xcoor', models.IntegerField()),
                ('ycoor', models.IntegerField()),
                ('rotate', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rollpaper.color')),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rollpaper.font')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rollpaper.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=100)),
                ('xcoor', models.IntegerField()),
                ('ycoor', models.IntegerField()),
                ('rotate', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rollpaper.paper')),
            ],
        ),
    ]
